apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: data-broker
  namespace: monitoring
  labels:
    app.kubernetes.io/name: data-broker
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: data-broker
  namespaceSelector:
    matchNames:
      - city-services
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
