apiVersion: v1
kind: Service
metadata:
  name: traffic-optimizer
  namespace: city-services
  labels:
    app.kubernetes.io/name: traffic-optimizer
spec:
  selector:
    app.kubernetes.io/name: traffic-optimizer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
