apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: inventors-manager-binding
  namespace: inventors
subjects:
  - kind: Group
    name: inventors-team
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: inventors-manager
  apiGroup: rbac.authorization.k8s.io
