apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traffic-optimizer
  namespace: city-services
  labels:
    app: traffic-optimizer
    component: stream-processor
spec:
  selector:
    matchLabels:
      app: traffic-optimizer
  endpoints:
    - port: metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - city-services
