apiVersion: v1
kind: Service
metadata:
  name: traffic-optimizer
  namespace: city-services
  labels:
    app: traffic-optimizer
    component: stream-processor
spec:
  selector:
    app: traffic-optimizer
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
  type: ClusterIP
