apiVersion: v1
kind: ServiceAccount
metadata:
  name: traffic-optimizer
  namespace: city-services
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/TrafficOptimizerMSKRole"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: anomaly-detector
  namespace: city-services
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/AnomalyDetectorMSKRole"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: energy-optimizer
  namespace: city-services
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/EnergyOptimizerMSKRole"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-broker
  namespace: city-services
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/DataBrokerMSKRole"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-connect
  namespace: city-services
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/KafkaConnectMSKRole"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: schema-registry
  namespace: city-services
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/SchemaRegistryMSKRole"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dlq-processor
  namespace: city-services
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/DLQProcessorMSKRole"
