apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds.yaml
  - operator-sa.yaml
  - operator-clusterrole.yaml
  - operator-clusterrolebinding.yaml
  - operator-deployment.yaml
