apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: energy-optimizer
spec:
  selector:
    matchLabels:
      app: energy-optimizer
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
