apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: data-broker
  labels:
    app: data-broker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-broker
  minReplicas: 5
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
