apiVersion: v1
kind: Service
metadata:
  name: data-broker
  labels:
    app: data-broker
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: metrics
  selector:
    app: data-broker
