apiVersion: v1
kind: ResourceQuota
metadata:
  name: inventors-quota
  namespace: inventors
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
    persistentvolumeclaims: "5"
    count/deployments.apps: "10"
    count/services: "10"
    count/secrets: "20"
    count/configmaps: "20"
