apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  env: development

resources:
  - ../../base/

transformers:
  - namespace-exclusion.yaml

patches:
  - path: patches/reduce-traffic-optimizer.yaml
    target:
      kind: Deployment
      name: traffic-optimizer
  - path: patches/reduce-energy-management.yaml
    target:
      kind: Deployment
      name: energy-management
