apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-operated.monitoring.svc:9090
        isDefault: true
        timeInterval: 15s
      - name: Loki
        type: loki
        url: http://loki.monitoring.svc:3100
        jsonData:
          maxLines: 1000
      - name: AMP
        type: prometheus
        url: https://aps-workspaces.ap-northeast-1.amazonaws.com/workspaces/${AMP_WORKSPACE_ID}/
        jsonData:
          sigV4Auth: true
          sigV4Region: ap-northeast-1
          sigV4AuthType: ec2_iam_role
