apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: city-services
  labels:
    app: schema-registry
    component: data-pipeline
spec:
  selector:
    app: schema-registry
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
