apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: agora-prometheus
  namespace: monitoring
spec:
  retention: 30d
  retentionSize: 20GB
  replicas: 1
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 25Gi
