apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: agora-prometheus
  namespace: monitoring
spec:
  retention: 90d
  retentionSize: 90GB
  replicas: 2
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 200Gi
