apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-optimizer
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: traffic-optimizer
              topologyKey: topology.kubernetes.io/zone
